### ISSUE TITLE
You don't have a logo

### ISSUE THREAD

**Issue by shinzlet** [haw230/the-anadromi-project#2]
![anadromi](https://user-images.githubusercontent.com/25427939/28382701-4f0d1f44-6c7c-11e7-87b3-a7807ef1cbcf.png)

**Comment by shinzlet** [comment]
There was a problem with that logo 
![anadromi fixed-01](https://user-images.githubusercontent.com/25427939/28382798-94c1eba0-6c7c-11e7-8805-5915b58958ff.png)

**Comment by haw230** [comment]
Check it again ;)



Also thanks, it's pretty nice.
